services:


  coppeliasim:
    image: murilomarinho/coppeliasim:noble_470rev4
    stop_signal: SIGINT
    platform: linux/amd64
    environment:
      DISPLAY: $DISPLAY # x server related
      ROS_DOMAIN_ID: 77
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ../../coppeliasim_scenes:/app/coppeliasim_scenes
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" # x server related
    ipc: "host"
    command: /bin/bash -c "
      sleep 3;
      cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh -s0 /app/coppeliasim_scenes/B1_with_Z1_showcase_simulation.ttt"

  whole_body_control:
    build:
      context: ../..  
      dockerfile: docker/sas_unitree_b1z1_rap_control_template/Dockerfile
    environment:
      DISPLAY: $DISPLAY  # x server related
      ROS_DOMAIN_ID: 77 # Set ROS domain ID for all ROS2 nodes
    privileged: true # Needed for some gpu configurations.
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" 
    ipc: "host"
    command: /bin/bash -c "
      source /opt/ros/jazzy/setup.bash;
      cd /app/software/ROS2/ros2_ws/ && colcon build && source install/setup.bash ;
      ros2 launch control_example control_example_b1z1_simulation_launch.py"

  sas_datalogger_server:
    image: murilomarinho/sas:jazzy # Set the image
    container_name: sas_datalogger_server_container # name the container
    stop_signal: SIGINT # define the signal used by Compose to stop the container
    stop_grace_period: 30s # specify how long Compose must wait when attempting to stop the container if it doesn't handle "stop_signal"
    # Set environment variables
    environment:
      PYTHONUNBUFFERED: 1 # enforce unbuffered output mode in Python
      ROS_DOMAIN_ID: 77 
    network_mode: "host" # x server related and for ROS2 networking
    ipc: "host"    
    volumes:
      - ./logs:/root/logs
    command: /bin/bash -c "
      cd /root/logs &&
      ros2 launch sas_datalogger  
      sas_datalogger_launch.py"