vfi_file_version: 2
zero_indexed: false
vfi_array:
    -
        vfi_type: "ROBOT_TO_ROBOT"
        cs_entity_one: ["B1_vfi_sphere_0"]
        cs_entity_two: ["Sphere_effector"]
        entity_one_primitive_type: "POINT"
        entity_two_primitive_type: "POINT"
        robot_index_one: 1
        robot_index_two: 1
        joint_index_one: 6
        joint_index_two: 12
        safe_distance: 0.5
        vfi_gain: 1.0
        direction: "RESTRICTED_ZONE"
        tag: "C1"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["x_inertial"]
        cs_entity_robot: ["/UnitreeB1_1/UnitreeZ1/line"]
        entity_environment_primitive_type: "LINE_ANGLE"
        entity_robot_primitive_type: "LINE_ANGLE"
        robot_index: 1
        joint_index: 12
        safe_distance: 5
        vfi_gain: 5.0
        direction: "SAFE_ZONE"
        tag: "C2"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_0"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_front_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C3"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_2"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_front_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C4"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_3"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_front_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C5"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_4"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_front_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C6"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_0"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_rear_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C7"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_2"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_rear_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C8"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_3"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_rear_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C9"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_4"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_rear_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C10"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_0"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_center_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C11"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_2"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_center_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C12"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_3"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_center_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C13"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Plane_frame_4"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_center_bumper"]
        entity_environment_primitive_type: "PLANE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.3
        vfi_gain: 0.41
        direction: "RESTRICTED_ZONE"
        tag: "C14"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Human_Cylinder"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_front_bumper"]
        entity_environment_primitive_type: "LINE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.7
        vfi_gain: 5.0
        direction: "RESTRICTED_ZONE"
        tag: "CH1"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Human_Cylinder"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_center_bumper"]
        entity_environment_primitive_type: "LINE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.7
        vfi_gain: 5.0
        direction: "RESTRICTED_ZONE"
        tag: "CH2"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Human_Cylinder"]
        cs_entity_robot: ["/UnitreeB1_1/B1_vfi_sphere_rear_bumper"]
        entity_environment_primitive_type: "LINE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 6
        safe_distance: 0.7
        vfi_gain: 5.0
        direction: "RESTRICTED_ZONE"
        tag: "CH3"
    -
        vfi_type: "ENVIRONMENT_TO_ROBOT"
        cs_entity_environment: ["Human_Cylinder"]
        cs_entity_robot: ["/UnitreeB1_1/UnitreeZ1/Sphere_effector"]
        entity_environment_primitive_type: "LINE"
        entity_robot_primitive_type: "POINT"
        robot_index: 1
        joint_index: 12
        safe_distance: 0.45
        vfi_gain: 5.0
        direction: "RESTRICTED_ZONE"
        tag: "CH4"
